### ISSUE TITLE
bug: Capturing log output doesn't seem to work (TS)

### ISSUE THREAD

**Issue by karamanliev** [Goose97/timber.nvim#12]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS Sequoia / Linux

### Describe the bug

Huge props for the plugin, it's amazing and the best of its kind in my experience.

I'm tring to make the capturing feature work in a react native project. I start the metro server with:
```shell
npx react-native start | tee /tmp/metro.log
```

This correctly writes the output to a file. I've checked multiple times.

Here's my plugin setup:
```lua
{
    'Goose97/timber.nvim',
    event = 'VeryLazy',
    config = function()
      require('timber').setup({
        log_templates = {
          watcher = {
            javascript = [[console.log('%watcher_marker_start', %log_target, '%watcher_marker_end')]],
            typescript = [[console.log('%watcher_marker_start', %log_target, '%watcher_marker_end')]],
            jsx = [[console.log('%watcher_marker_start', %log_target, '%watcher_marker_end')]],
            tsx = [[console.log('%watcher_marker_start', %log_target, '%watcher_marker_end')]],
          },
        },
        log_watcher = {
          enabled = true,
          sources = {
            ts = {
              type = 'filesystem',
              name = 'Log file',
              path = '/tmp/metro.log',
            },
          },
          preview_snippet_length = 32,
        },
      })

      vim.keymap.set('n', 'glf', function()
        return require('timber.buffers').open_float()
      end, { desc = 'Open log float' })

      vim.keymap.set('n', 'glw', function()
        require('timber.actions').insert_log({ template = 'watcher', position = 'below' })
      end, { desc = 'Log watcher' })
    end,
  }
```

Inside any file when i hit `glw` on a variable the plugin correctly creates logs like
```js
  console.log('🪵XAK|', varFoo, '|XAK');
  console.log('🪵O4M|', varBar, '|O4M');
```

I check the log file with `cat /tmp/metro.log` and confirm that the logs are indeed there:
```
🪵XAK| true |XAK
🪵O4M| false |O4M
```

 But when i try to open the float inside the file I get:
`(timber) Log placeholder has no content`

Am I doing something wrong or this is a bug? I've tried many different things with no success and I really want to use this feature.

### Steps To Reproduce

1. Start server which outputs console to a file
2. Create logs with watcher markers
3. Try to open float preview on the watched logs
4. Get "log placeholder has no content" error

### Expected Behavior

Float preview show the logged value.

**Comment by Goose97** [comment]
Thanks for the details writeup. It really helps. Before I can look into this more thoroughly, can you do a couple quick check? 

According to your step to reproduce, I see that you start the server first then create the log. My wild guess is that it got something to do with the order of the events. The plugin starts tailing the log file as soon as the plugin is setup. If the log is written to the file before that, the log output will be lost.

To rule out this scenario, can you wrap the log statement into a setInterval, like this:
```javascript
  setInterval(() => {
    const a = 123
    console.log('🪵H42|', a, '|H42')
  }, 1000)
```

In the mean time, I will add some debugging logs so we'll have an easier time catching this bug.

**Comment by karamanliev** [comment]
Hello, thank you for taking out of your time to help. I tried to wrap the logging inside a `setInterval`, but unfortunately I still do get the `Log placeholder has no content`. On the left is neovim, on the top right is the metro console and on the bottom right is the output of `cat /tmp/metro.log`.

![image](https://github.com/user-attachments/assets/864e0e7b-06b5-4bb8-9787-e262feb7abb3)

**Comment by Goose97** [comment]
I get it. You log has a LOG prefix in front. [This commit](https://github.com/Goose97/timber.nvim/commit/7cb8f076abefe3806a2295205315fb2b0dd73a9c) should fix it.

Previously, I only match the pattern at the beginning of the line, so it performs a bit better. However, this is a valid use case. See if it fixes your problem.

Also, fyi, you can enable syntax highlight for the float buffer [like this](https://github.com/Goose97/timber.nvim/blob/main/doc/RECIPES.md#pretty-captured-log-buffer).

**Comment by karamanliev** [comment]
Oooh, niceeeee! I can confirm that it is working now, thank you!
