### ISSUE TITLE
feature: %filename template variable

### ISSUE THREAD

**Issue by ruicsh** [Goose97/timber.nvim#16]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

When having serveral log statements in a project, it's useful to know which file each log originated from. I'd like to customize my log statements like this (for lua, as an example):
```lua
lua = [[print("%filename:%line_number %log_target=" .. vim.inspect(%log_target))]],
```
for a result of:
```lua
print("timber.lua:32 foo=" .. vim.inspect(foo))
```

### Describe the solution you'd like

A new template variable, maybe %filename

### Describe alternatives you've considered

I don't think I can find an alternative when using timber.nvim

**Comment by Goose97** [comment]
Thanks for the suggestion. The new placeholder is `%filename`, it should work now.
