### ISSUE TITLE
feature: automatic plain log text

### ISSUE THREAD

**Issue by ruicsh** [Goose97/timber.nvim#17]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

When adding a plain log, the default behavior is to prompt the user to write something by using the %insert_cursor template variable. 

My main workflow is to use these plain logs as simple signals of "the code ran through here". For this, I always would like to log the same, not be asked to write something each time.

### Describe the solution you'd like

Maybe, two new template variables:
- %line - a trimmed, truncated to 50chars copy of the line where the user keyed in the timber command
- %placement - `above`/`below` depending on the command

```lua
lua = [[print("%filename:%line_number (%placement %line)")]]
```
`|` is the cursor where the user keys in `glo`
```lua
      loc|al foo = "bar"
```
would result in:
```lua
      loc|al foo = "bar"
      print("timber.nvim:32 (after local foo = bar)")
```
if the lien is longer than 50chars, truncates the text with `...` at the end.

### Describe alternatives you've considered

I don't think I can find an alternative when using timber.nvim

**Comment by Goose97** [comment]
This is easy to implement. But I think we better implement some mechanism for users to implement their own placeholder with a callback. For example, config could look like this:

```lua
opts = {
  template_placeholder = {
    line = function(log_target_ts_node, log_target_text, placement)
      -- return the content to replace here
    end,
  }
}
```

**Comment by ruicsh** [comment]
yes that would be great, maybe call it `%custom` instead of `%line`?

**Comment by Goose97** [comment]
This should be ok now @ruicsh. Your usecase could be done like this:

```lua
opts = {
  template_placeholders = {
    line = function()
      return vim.fn.getline(".")
    end,
    placement = function(ctx)
      return ({
        above = "before",
        below = "after",
      })[ctx.log_position]
    end,
  },
  log_templates = {
    plain = {
      -- We can use the custom defined placeholder here
      lua = [[print("%filename:%line_number (%placement %line)")]]
    }
  }
}
```

**Comment by ruicsh** [comment]
works great!
here's my config
```lua
template_placeholders = {
  snippet = function()
    return vim.trim(vim.fn.getline(".")):gsub('"', ""):sub(1, 50)
  end,
  placement = function(ctx)
    return ctx.log_position == "above" and "before" or "after"
  end,
},
log_templates = {
  plain = {
    lua = [[print("%filename:%line_number (%placement %snippet)")]],
  }
}
```
produces this:
```lua
local foo = { bar = "baz" }
print("timber.lua:2 (after local foo = { bar = baz })")
```
