### ISSUE TITLE
bug: log class properties in JS/TS

### ISSUE THREAD

**Issue by ruicsh** [Goose97/timber.nvim#20]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

On JS/TS code, I can't insert a log variable for class properties.

### Steps To Reproduce

taking this code, with `|` meaning the cursor position:
```ts
class Foobar {
  foo = 1;

  bar() {
    this.f|oo = 2;
  }
}
```
if I hit `glv`, it doesn't insert any log

### Expected Behavior

it should insert a log variable like:
```ts
class Foobar {
  foo = 1;

  bar() {
    this.f|oo = 2;
    console.log("this.foo", this.foo)
  }
}
```

**Comment by Goose97** [comment]
Please check if this works

**Comment by ruicsh** [comment]
works great, cheers!
